package com.example.awslambda.customer.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * <p>
 *
 * </p>
 *
 * @author Administrator
 * @since 2019-07-06
 */
@Data
@DynamoDBTable(tableName = "customer")
public class Customer {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  private String name;
  private String email;
}
